controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_react_index:
    path: /{route}
    defaults:
        _controller: App\Controller\YourReactController::index
    requirements:
        route: "^(?!api|_(profiler|wdt)).*"